name: Regression

on:
  workflow_dispatch:  
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my_docker_project:$(date +%s)

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
        
    #- name: Build with Maven
    #  run: mvn post-integration-test
      
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: cluecumber-report
        path: target\generated-report
        retention-days: 30
