name: Regression

on:
  workflow_dispatch:  
  push:
    branches: [ "develop", "master" ]
  pull_request:
    branches: [ "develop", "master" ]

jobs:
 
  test:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
        
    - name: Build with Maven
      run: mvn post-integration-test
      
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: cluecumber-report
        path: ./target/generated-report
        retention-days: 30
        
    - name: Setup Pages
      uses: actions/configure-pages@v2
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./target/generated-report
        
    #- name: Deploy report to Github Pages
     # if: always()
     # uses: peaceiris/actions-gh-pages@v2
    #  env:
    #    PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #    PUBLISH_BRANCH: gh-pages
     #   PUBLISH_DIR: cluecumber-history
      
          
    - name: Deploy to GitHub Pages
      if: always()
      id: deployment
      uses: actions/deploy-pages@v1
